### ISSUE TITLE
Consider environment variables with empty values

### ISSUE THREAD

**Issue by kei2100** [kayac/go-config#43]
空の値で定義される環境変数 FOO を `x{{ env "FOO" "DEFAULT" }}x` で展開した場合、`xx` とは出力されず、FOO が未定義の場合と同様に `xDEFAULTx` となるようです。

`env` による環境変数の取得には os.Getenv が使用されており、
https://github.com/kayac/go-config/blob/cec48758837572cf279afc32d9b613962aae4dfd/config.go#L184

空の値で定義される場合と未定義の場合とで区別なく扱われるためだと認識していますが、 こちらは go-config の意図通りの挙動でしょうか。

以下再現コードになります。
https://play.golang.org/p/XUjO2XkD8pS

**Comment by fujiwara** [comment]
must_env 関数を増やした際に、定義済みで空文字列の場合に panic させたくないため os.LookupEnv() を使用したのですが、その時点で env 関数も LookupEnv に変えるべきだったのですが、変えずにそのままになっていた、というのが実情のようです。

整合性を考えると env 関数も os.LookupEnv にするべきだと思いますが、既存のバージョンと互換性が壊れてしまうので、バージョン 1 を出す際の変更になると思います。v0.x のうちは現状の挙動のまま、という想定で利用してもらえますでしょうか。

**Comment by kei2100** [comment]
@fujiwara 

> 整合性を考えると env 関数も os.LookupEnv にするべきだと思いますが、既存のバージョンと互換性が壊れてしまうので、バージョン 1 を出す際の変更になると思います。v0.x のうちは現状の挙動のまま、という想定で利用してもらえますでしょうか。

承知しました。

AWS ECS へのデプロイに ecspresso を利用させていただいており、タスク定義に空文字の環境変数を埋め込みたいケースがあったのですが、ISSUE にあげた通りデフォルト値で上書きされてしまったので確認させていただきました。ひとまず空文字の代わりに特定文字を環境変数に設定し、Go 標準の template 記法で空文字に置換するなどしてワークアラウンドしたいと思います。

回答いただきありがとうございました。

**Comment by ken39arg** [comment]
2年前へのレスですが...
https://pkg.go.dev/github.com/kayac/go-config#LoadWithEnv

- envは環境変数が未設定(または空文字)の場合、別の環境変数またはデフォルト文字列にfallbackする
- must_envは環境変数が存在することを保証する

という明確な違いがあります。

上記の場合はmust_envを使うべきだと思います。
またLookupEnvにしてしまうと、fallback & defaultの実装が難しくなるので難しいかなあと個人的には思います

以下のような使い方を想定しているのがenvです

```yaml
mysql:
   rw_host: {{ env "DB_RW_HOST" "DB_HOST" "mysql" }}
   ro_host: {{ env "DB_RO_HOST" "DB_HOST" "mysql" }}
   rw_user: {{ env "DB_RW_USER" "DB_USER" "rwuser" }}
   ro_user: {{ env "DB_RO_USER" "DB_USER" "rouser" }}
```

DBが１インスタンスの場合にreader/writerのユーザーを分けて起動するとき、DBインスタンスがreader/writerに分かれていてホストが複数でユーザーは単一のケース、docker-compose用(default値)
みたいな使い方をしていました。ときとともに運用方法が変わってほぼほぼmust_envでOKみたいな感じにはなってきていますが、自分はenvでのfallback未だにめちゃくちゃ使っています 😄 

envで空文字を使いたい時は `{{ env "FOO" "BAR" "" }}`
